INSERT INTO ProfissionalSaude
(CodProfissional, CRM, NomeSocial, NomeCivil, Profissao)
VALUES
(0, 'CRM/MG 794772', NULL, 'Mariah Aparecida', 'Veterinário'),
(1, 'CRM/GO 536110', NULL, 'Thomas Mendonça', 'Médico'),
(2, NULL, NULL, 'Liz Mendes', 'Nutricionista'),
(3, 'CRM/MS 611720', NULL, 'Sr. Thiago Carvalho', 'Terapeuta Ocupacional'),
(4, 'CRM/BA 295528', NULL, 'Davi Miguel Sá', 'Fonoaudiólogo'),
(5, NULL, NULL, 'José Nascimento', 'Educador Físico'),
(6, NULL, NULL, 'Dra. Clara das Neves', 'Biomédico'),
(7, 'CRM/PI 739426', NULL, 'Brayan Rodrigues', 'Ortopedista'),
(8, 'CRM/BA 325213', NULL, 'Dr. Carlos Eduardo Fogaça', 'Ortopedista'),
(9, NULL, NULL, 'Luara Pimenta', 'Assistente Social'),
(10, 'CRM/RO 346236', NULL, 'Gabrielly Novaes', 'Ortopedista'),
(11, 'CRM/AM 370977', NULL, 'Melina Moreira', 'Fonoaudiólogo'),
(12, 'CRM/RN 671532', NULL, 'Bento Novaes', 'Fisioterapeuta'),
(13, 'CRM/PR 464197', NULL, 'Caleb Silveira', 'Fonoaudiólogo'),
(14, 'CRM/AL 844132', NULL, 'Agatha Pimenta', 'Farmacêutico'),
(15, 'CRM/AC 097802', 'Lívia da Cruz', 'Sra. Ana Luiza Correia', 'Ortopedista'),
(16, 'CRM/MG 744754', 'Hellena da Costa', 'Yago Machado', 'Veterinário'),
(17, NULL, NULL, 'Bruno Dias', 'Técnico de Enfermagem'),
(18, NULL, NULL, 'Rebeca Caldeira', 'Biomédico'),
(19, 'CRM/MT 255759', 'Yuri da Rocha', 'Srta. Lívia Nogueira', 'Veterinário'),
(20, 'CRM/RR 912755', NULL, 'Yan Pastor', 'Fisioterapeuta'),
(21, NULL, NULL, 'Pedro Miguel Borges', 'Psicólogo'),
(22, NULL, NULL, 'Maria Isis Dias', 'Psicólogo'),
(23, NULL, NULL, 'Isabella da Rocha', 'Educador Físico'),
(24, NULL, NULL, 'Gabriel Cirino', 'Educador Físico'),
(25, 'CRM/AP 084353', NULL, 'José Pedro Melo', 'Terapeuta Ocupacional'),
(26, 'CRM/PE 978147', NULL, 'Caio Rocha', 'Ortopedista'),
(27, NULL, NULL, 'Dom Andrade', 'Enfermeiro'),
(28, 'CRM/MA 740883', NULL, 'Vitor Hugo Rodrigues', 'Fonoaudiólogo'),
(29, 'CRM/MT 854030', NULL, 'Valentina da Mota', 'Fonoaudiólogo');
